[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"
authors = ["Hemant Rajput <rajput.hemant2001@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7.0"

